spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    debug: true  # 필터 체인 디버그 프린트 (dev에서만 추천)

server:
  port: 8080

# dev/test 전용 옵션 예시
app:
  dev-header-auth: true


logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 99221206305-3hv46i66gmo27oug2uno8mn7qh9v80fh.apps.googleusercontent.com
      secret: ${GOOGLE_CLIENT_SECRET}
    callback:
      url: http://localhost:8080/login/google
    token:
      url: https://oauth2.googleapis.com/token

  kakao:
    url: https://kauth.kakao.com/oauth/authorize
    client:
      id: e7680efe3200964b658d4f23796af5a6
      secret: ${KAKAO_CLIENT_SECRET}
    callback:
      url: http://localhost:8080/login/kakao
    token:
      url: https://kauth.kakao.com/oauth/token

  naver:
    url: https://nid.naver.com/oauth2.0/authorize
    client:
      id: nUZ4CJJSLTxiMP53ZKid
      secret: ${NAVER_CLIENT_SECRET}
    callback:
      url: http://localhost:8080/login/naver
    token:
      url: https://nid.naver.com/oauth2.0/token

jwt:
  secret: ${JWT_SECRET}